all: *.cpp
	$(CXX) test1.cpp -std=c++17 -g -O3 -Werror -Wall -Wextra -pthread -pedantic -o test1
	$(CXX) test2.cpp -std=c++17 -g -O3 -Werror -Wall -Wextra -pthread -pedantic -o test2
	$(CXX) test3.cpp -std=c++17 -g -O3 -Werror -Wall -Wextra -pthread -pedantic -o test3

clean:
	rm -f test1
	rm -f test2
	rm -f test3

